name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-24.04
      steps:
        - name: Print Hello
          run: echo "Hello World!\nWelcome to the world of DevOps"
        - name: Print Bye
          run: echo "Goodbyeee...."
