name: First Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Welcome to the world of Clouds!!
          echo Welcome to the world of DevOps!!
